import { ButtonOutlined } from 'components/Button'
import { AutoColumn } from 'components/Column'
import ProjectImage from 'components/ProjectImage'
import { Link, RouteComponentProps } from 'react-router-dom'
import styled from 'styled-components/macro'

import BlockshotOne from '../../assets/images/blockshotOne.png'
// import ArtByMann1 from '../../assets/images/artbymann1.mp4'
import CarmelCover from '../../assets/images/carmelCover.png'
import DetachOne from '../../assets/images/detach1.png'
import DetachTwo from '../../assets/images/detach2.png'
import DetachThree from '../../assets/images/detach3.png'
import MeImage from '../../assets/images/me.jpg'
import MintUICover from '../../assets/images/mintUICover.png'
import Row, { RowBetween } from '../../components/Row'
import { useDefaultsFromURLSearch } from '../../state/swap/hooks'
import { ExternalLink, ThemedText, Z_INDEX } from '../../theme'
import AppBody from '../AppBody'
import {
  ArtByMannProject,
  Blockshot,
  CarmelProject,
  DetachProject,
  HPDSProject,
  MintUIProject,
  PortalsProject,
  ShreddersDigestProject,
} from '.'
import ProjectCard, { ProjectTags } from './ProjectCard'
import ProjectPageContainer from './ProjectPageContainer'
export const Grid = styled(AutoColumn)`
  display: grid;
  height: 100%;
  width: 100%;

  padding-top: 0px;
  position: relative;
  top: 0;

  align-items: start;
  align-content: space-between;
  grid-template-columns: 1fr 1fr 1fr;

  grid-gap: 20px;

  // overflow-x: visible !important;

  ${({ theme }) => theme.mediaWidth.upToLarge`
  grid-template-columns: 1fr 1fr ;
`};
  ${({ theme }) => theme.mediaWidth.upToMedium`
  grid-template-columns: 1fr 1fr;
`};
  ${({ theme }) => theme.mediaWidth.upToSmall`
  grid-template-columns: 1fr ;
`};
`

export function PortalsPage({ history }: RouteComponentProps) {
  return (
    <>
      <ProjectPageContainer project={PortalsProject}>
        <ThemedText.Main>
          {`Last fall, I started an NFT project called Innermind using a generative art algorithm I had worked on for a
          few months. The art pieces, called Portals, were generated using WebGL with some layers generated by GAN
          models from old projects. All the code, art, and design associated with the project were by me. The mint
          didn't go as well as we had hoped (it turns out the NFT world prefers PFP projects), so I decided to move on
          from the project. But, it's how I got started working in web3.`}
        </ThemedText.Main>
        <ProjectImage src={'https://innermind-01.s3.us-west-1.amazonaws.com/e8ec85.mp4'} size={'80%'}></ProjectImage>
        <ThemedText.Main>
          {` The mint didn't go as well as we had hoped (turns out the NFT world prefers PFP projects) so I decided to move on from the project. But it's how I got
          started working in web3.`}
        </ThemedText.Main>
        <ButtonOutlined as={ExternalLink} href={'https://innermind.space/portals'}>
          Take a look
        </ButtonOutlined>
      </ProjectPageContainer>
    </>
  )
}

export function CarmelPage({ history }: RouteComponentProps) {
  return (
    <>
      <ProjectPageContainer project={CarmelProject}>
        <ThemedText.Main>
          Carmel is an experiment aimed at making Solana human-readable. Using a Golang backend, it parses the
          blockchain and updates the UI with the latest data.
        </ThemedText.Main>
        <ProjectImage src={CarmelCover} size={'80%'}></ProjectImage>
        <ButtonOutlined as={ExternalLink} href={'https://carmel-beta.vercel.app/#/top'}>
          Check it out
        </ButtonOutlined>
      </ProjectPageContainer>
    </>
  )
}

export function MintUIPage({ history }: RouteComponentProps) {
  return (
    <>
      <ProjectPageContainer project={MintUIProject}>
        <ThemedText.Main>
          Mint UI is an open-source minting tool I developed and released under the{' '}
          <ExternalLink href="/portals">Innermind</ExternalLink>
          {` brand. It was the first tool to enable the minting of NFTs on Solana without touching code. It was a one-night build, and I didn't expect much usage, but it ended up somewhat popular. It's currently at around 150 stars on GitHub.`}
        </ThemedText.Main>
        <ProjectImage
          src={'https://user-images.githubusercontent.com/28356568/135772190-7c387046-b9e6-4427-8099-fac81728e900.mp4'}
          size={'100%'}
        ></ProjectImage>
        <ButtonOutlined as={ExternalLink} href={'https://github.com/InnerMindDAO/MintUI/'}>
          GitHub
        </ButtonOutlined>
      </ProjectPageContainer>
    </>
  )
}
export function DetachPage({ history }: RouteComponentProps) {
  return (
    <>
      <ProjectPageContainer project={DetachProject}>
        <ThemedText.Main>
          Detach was an iOS App I made for time management. Utilizing a proprietary VPN setup, the app filtered network
          request from distracting apps. Apple removed the app from the App Store in March 2020 due to changes to their
          Networking SDK policies. Before it was removed from the App Store it was a great playground to experiment with
          mobile design. Built with React Native.
        </ThemedText.Main>
        <Row>
          <ProjectImage src={DetachOne} size={'32%'} modalSize={'33%'}></ProjectImage>
          <ProjectImage src={DetachTwo} size={'32%'} modalSize={'33%'}></ProjectImage>
          <ProjectImage src={DetachThree} size={'32%'} modalSize={'33%'}></ProjectImage>
        </Row>
        {/* <ButtonOutlined as={ExternalLink} href={'https://github.com/InnerMindDAO/MintUI/'}>
          GitHub
        </ButtonOutlined> */}
      </ProjectPageContainer>
    </>
  )
}
export function ArtByMannPage({ history }: RouteComponentProps) {
  return (
    <>
      <ProjectPageContainer project={ArtByMannProject}>
        <ThemedText.Main>
          {`Art by Mann is a collection of art pieces I made using the latent space in a PGGAN model. I've been working on
          AI Art since 2018 (actually submitted GAN art for the AP Art Test) and think I have a fairly unique artistic
          process involving incremental tweaks to the target data and then utilizing the latent space to create moving
          pieces.`}
        </ThemedText.Main>
        <ThemedText.Main>
          {`I know some people consider AI Art controversial, but I think they're just fun to look at!`}
        </ThemedText.Main>
        <Row>
          <ProjectImage
            src={'https://www.artbymann.net/static/STRIPES-f97b40e3b3f4ba6e00c257a01d37f261.mp4'}
            size={'49%'}
            modalSize={'50%'}
          ></ProjectImage>
          <ProjectImage
            src={'https://www.artbymann.net/static/PHoTOSYNTHESUS-126b4e1c16bf734ddae9db3953ce9334.mp4'}
            size={'49%'}
            modalSize={'50%'}
          ></ProjectImage>
          {/* <ProjectImage src={DetachThree} size={'49%'}></ProjectImage> */}
        </Row>
        <ThemedText.Main>
          {`I know some people consider AI Art controversial, but I think they're just fun to look at!`}
        </ThemedText.Main>
        <ButtonOutlined as={ExternalLink} href={'artbymann.net'}>
          artbymann.net
        </ButtonOutlined>
      </ProjectPageContainer>
    </>
  )
}

export function ShreddersPage({ history }: RouteComponentProps) {
  return (
    <>
      <ProjectPageContainer project={ShreddersDigestProject}>
        <ThemedText.Main>
          Helped lead clothing design at Shredders Digest, a clothing company led by Zio Ziegler. It was a fantastic
          learning experience and a lot of fun.
        </ThemedText.Main>
        <ButtonOutlined as={ExternalLink} href={'https://shredders-digest.com/'}>
          Shredders Digest
        </ButtonOutlined>
      </ProjectPageContainer>
    </>
  )
}

export function HPDSPage({ history }: RouteComponentProps) {
  return (
    <>
      <ProjectPageContainer project={HPDSProject}>
        <ThemedText.Main>
          Worked under Prof. James Landay to develop design systems for improving work enviroments while optimising for
          human-wellbeing.
        </ThemedText.Main>
      </ProjectPageContainer>
    </>
  )
}
export function BlockshotPage({ history }: RouteComponentProps) {
  return (
    <>
      <ProjectPageContainer project={Blockshot}>
        <ThemedText.Main>
          Weekend project. A simple site to show display all NFTs introducted to Ethereum each block.
        </ThemedText.Main>
        <ProjectImage src={BlockshotOne} size={'100%'}></ProjectImage>
        <ButtonOutlined as={ExternalLink} href={'https://github.com/lukejmann/blockshot'}>
          GitHub
        </ButtonOutlined>
      </ProjectPageContainer>
    </>
  )
}
